In [1]:
import pandas as pd

data_train = pd.read_csv("data/cat_train.csv")
data_train.info

<bound method DataFrame.info of             id  bin_0  bin_1  bin_2 bin_3 bin_4 nom_0      nom_1    nom_2  \
0            0    0.0    0.0    0.0     F     N   Red  Trapezoid  Hamster   
1            1    1.0    1.0    0.0     F     Y   Red       Star  Axolotl   
2            2    0.0    1.0    0.0     F     N   Red        NaN  Hamster   
3            3    NaN    0.0    0.0     F     N   Red     Circle  Hamster   
4            4    0.0    NaN    0.0     T     N   Red   Triangle  Hamster   
...        ...    ...    ...    ...   ...   ...   ...        ...      ...   
599995  599995    0.0    1.0    0.0     T     N   Red    Polygon  Axolotl   
599996  599996    1.0    0.0    0.0     T     Y  Blue    Polygon      Dog   
599997  599997    0.0    0.0    0.0     F     Y   Red     Circle  Axolotl   
599998  599998    1.0    1.0    0.0     F     Y   NaN    Polygon  Axolotl   
599999  599999    0.0    0.0    0.0     T     N  Blue   Triangle      Dog   

             nom_3  ...      nom_9 ord_0   

In [2]:
data_train.head()

id  bin_0  bin_1  bin_2 bin_3 bin_4 nom_0      nom_1    nom_2       nom_3  \
0   0    0.0    0.0    0.0     F     N   Red  Trapezoid  Hamster      Russia   
1   1    1.0    1.0    0.0     F     Y   Red       Star  Axolotl         NaN   
2   2    0.0    1.0    0.0     F     N   Red        NaN  Hamster      Canada   
3   3    NaN    0.0    0.0     F     N   Red     Circle  Hamster     Finland   
4   4    0.0    NaN    0.0     T     N   Red   Triangle  Hamster  Costa Rica   

   ...      nom_9 ord_0        ord_1     ord_2 ord_3 ord_4  ord_5  day month  \
0  ...  02e7c8990   3.0  Contributor       Hot     c     U     Pw  6.0   3.0   
1  ...  f37df64af   3.0  Grandmaster      Warm     e     X     pE  7.0   7.0   
2  ...        NaN   3.0          NaN  Freezing     n     P     eN  5.0   9.0   
3  ...  f9d456e57   1.0       Novice  Lava Hot     a     C    NaN  3.0   3.0   
4  ...  c5361037c   3.0  Grandmaster      Cold     h     C     OZ  5.0  12.0   

  target  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 25 columns]

In [3]:
data_train.ord_2.value_counts()

ord_2
Freezing       142726
Warm           124239
Cold            97822
Boiling Hot     84790
Hot             67508
Lava Hot        64840
Name: count, dtype: int64

In [4]:
mapping = {
    "Freezing": 0,
    "Warm": 1,
    "Cold": 2,
    "Boiling Hot": 3,
    "Hot": 4,
    "Lava Hot": 5
}
data_train.loc[:, "ord_2"] = data_train.ord_2.map(mapping)
data_train.ord_2.value_counts()

ord_2
0.0    142726
1.0    124239
2.0     97822
3.0     84790
4.0     67508
5.0     64840
Name: count, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
data_train = pd.read_csv("data/cat_train.csv")
data_train.loc[:, "ord_2"] = data_train.ord_2.fillna("NONE")

lbl_enc = LabelEncoder()

data_train.loc[:, "ord_2"] = lbl_enc.fit_transform(data_train.ord_2.values)
data_train.ord_2.value_counts()

ord_2
2    142726
6    124239
1     97822
0     84790
3     67508
4     64840
5     18075
Name: count, dtype: int64

In [7]:
import numpy as np
from scipy import sparse

example = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [1, 0, 1]
])

sparse_example = sparse.csr_matrix(example)
sparse_example.data, sparse_example.data.nbytes, sparse_example.indices, sparse_example.indptr, sparse_example.shape

(array([1, 1, 1, 1], dtype=int32),
 16,
 array([2, 0, 0, 2]),
 array([0, 1, 2, 4]),
 (3, 3))